name: Daily Coding Problem

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: python generator.py

      - run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "Daily update" || echo "No changes"
          git push
